### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by heqingbao** [geftimov/android-id-card-reader#1]
```
02-24 11:26:27.851 5567-5567/com.eftimoff.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.eftimoff.myapplication, PID: 5567
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.eftimoff.myapplication-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libpngt.so"
 at java.lang.Runtime.loadLibrary(Runtime.java:366)
 at java.lang.System.loadLibrary(System.java:989)
 at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:43)
 at com.eftimoff.idcardreader.components.tesseract.TesseractImpl.<init>(TesseractImpl.java:41)
 at com.eftimoff.idcardreader.components.tesseract.TessaractModule.provideTesseract(TessaractModule.java:43)
 at com.eftimoff.idcardreader.components.tesseract.TessaractComponent.provideTesseract(TessaractComponent.java:23)
 at com.eftimoff.idcardreader.ui.camera.ShowCameraFragment.setupComponents(ShowCameraFragment.java:93)
 at com.eftimoff.idcardreader.ui.common.BaseFragment.onViewCreated(BaseFragment.java:30)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
 at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
 at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1223)
 at android.app.Activity.performStart(Activity.java:5999)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2408)
 at android.app.ActivityThread.access$800(ActivityThread.java:144)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5277)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
```

**Comment by geftimov** [comment]
This project is still in development and it is not made as library yet , sorry.
